### ISSUE TITLE
Examples?

### ISSUE THREAD

**Issue by TGit-Tech** [sim1234/MiniApache#1]
No wiki, no examples on arduino.cc - Guess I'm digging into this project manually.  It would be really nice to have at least a few examples somewhere.  Or perhaps I've overlooked where they may be?

**Comment by sim1234** [comment]
Working on it :)

**Comment by TGit-Tech** [comment]
If it helps your project any; I've added the following code to WebServerST
code to truncate web files to an 8.3 format.  Seems SD.h only takes on 8.3
file formats although there is a SdFatLib to overcome this.  I skipped that
library just for simplicity.  Guess I'm gathering the code isn't at a
releasable state quite yet?

```
        // File Name (Modify for 8.3)
        DBG((F("SD file = "))); DBGL((fileName));
        pch = strrchr(fileName,'.');                          //ptr to
```

extension
            if(pch>0){memcpy(ext,pch,4);pch[0]='\0';}
//ext=4-digit copy, truncate name
            pch = strrchr(fileName,'/');                          //ptr to
filename
            if(strlen(pch)>9) { pch[7]='~';pch[8]='1';pch[9]='\0'; }
//Truncate fileName to 8-digits
            strcat(fileName,ext);                                 //Concate
extension
            DBG((F("SD file(8.3) = "))); DBGL((fileName));
